name: Delete Old Log Files
on:
  push:
    branches:
      - main

jobs:
  delete-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Deleting log files older than 7 days..."  # Print message to log
      
      - name: Delete log files
        run: |
          if [ -d "logs/" ]; then
            find logs/ -type f -mtime +7 -exec rm -f {} \;
          else
            echo "Directory logs/ does not exist. Skipping log deletion."
          fi
