name: Deploy to Azure
on:
  push:
    branches:
      - main          # Trigger the workflow when code is pushed to 'main'
  pull_request:
    branches:
      - main          # Trigger the workflow on pull requests to 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Parse Azure Credentials
        id: parse_creds
        run: echo "${{ toJSON(secrets.AZURE_CREDENTIALS) }}" | jq '.clientId, .clientSecret, .subscriptionId, .tenantId'

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}         
          tenant-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
          subscription-id: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
          client-secret: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}

      - name: Run Tests
        run: npm test                                       # Add a step to run tests before deployment

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "my-first-app02"                        # Update the app name here
          package: .
