name: Deploy to Azure
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ fromJson(secrets.AZURE_CREDENTIALS2).clientId }}
          tenant-id: ${{ fromJson(secrets.AZURE_CREDENTIALS2).tenantId }}
          subscription-id: ${{ fromJson(secrets.AZURE_CREDENTIALS2).subscriptionId }}
          client-secret: ${{ fromJson(secrets.AZURE_CREDENTIALS2).clientSecret }}

      - name: Run Tests
        run: npm test

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "my-first-app02"
          package: .
