name: Deploy to Azure
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [staging, production]  # Define multiple environments

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS2 }}

      - name: Run Tests
        run: npm test  # Adjust based on your testing framework

      - name: Display Deployment Start
        run: echo "Starting deployment to Azure..."  # Output message to indicate the start of the deployment

      - name: Deploying code to Azure App Service
        run: echo "Deploying code to Azure App Service..."  # Output message for progress tracking

      - name: Deploy if tests pass
        if: success()  # Only deploy if tests pass
        uses: azure/webapps-deploy@v2
        with:
          app-name: "my-first-app02"
          package: .

      - name: Rollback if deployment fails
        if: failure()  # Roll back if the previous step fails
        run: echo "Rolling back to the previous stable version..."
